DELETE FROM faqs;

INSERT INTO faqs (question, answer, category, active) VALUES
('How do I book a consultation?', 'You can book a free discovery call directly on our website at fitlogic.com/book, or reply to any of our emails with your preferred date and time. Discovery calls are 15 minutes and help us understand your goals before committing.', 'Appointment_Scheduling', true),
('What happens during the initial consultation?', 'Your first consultation is a comprehensive 60-minute session where we review your health history, current symptoms, lifestyle factors, and goals. We''ll create a personalized roadmap and discuss which of our programs is the best fit. You''ll leave with clear next steps.', 'Appointment_Scheduling', true),
('Do you offer virtual consultations?', 'Yes! We offer both in-person and virtual consultations via secure video. Most of our clients start with a virtual discovery call, and many continue their entire program remotely. Same quality, same results — from anywhere.', 'Appointment_Scheduling', true),
('How long until I can get an appointment?', 'Discovery calls are typically available within 3-5 business days. For returning clients, follow-up appointments are usually available within 1-2 weeks. We prioritize continuity of care for active program participants.', 'Appointment_Scheduling', true),
('What programs do you offer?', 'We offer three core programs:\n\n1. Hormone Optimization — A 12-week protocol for men and women experiencing fatigue, weight gain, or hormonal imbalances\n2. Gut Health Reset — An 8-week program addressing digestive issues, food sensitivities, and inflammation\n3. Executive Wellness — Ongoing optimization for high-performers including quarterly labs, biometric tracking, and personalized protocols\n\nEach program includes lab work, 1-on-1 coaching, and a customized plan.', 'Prescription_Lab_Requests', true),
('What kind of lab work do you order?', 'We run comprehensive panels that go far beyond standard bloodwork. This typically includes advanced hormonal panels, thyroid markers (full panel, not just TSH), metabolic markers, inflammatory markers, nutrient levels, and gut health testing when indicated. All labs are included in your program fee.', 'Prescription_Lab_Requests', true),
('How is functional medicine different from regular healthcare?', 'Traditional medicine focuses on diagnosing and treating disease. Functional medicine focuses on finding and addressing the root cause of your symptoms. We spend 10x more time with you, run more comprehensive labs, and create personalized protocols — not one-size-fits-all prescriptions. Our goal is optimization, not just normal.', 'Prescription_Lab_Requests', true),
('Do you offer group programs?', 'Yes! We run group cohorts for our Hormone Optimization and Gut Health Reset programs quarterly. Groups are limited to 12 people for personalized attention. Group programs are 40% less than 1-on-1 and include community support, weekly group calls, and all the same lab work.', 'Prescription_Lab_Requests', true),
('What kind of results can I expect?', 'Results vary by program and individual, but most clients report significant improvements within 4-6 weeks. Common outcomes include: better energy levels (reported by 89% of clients), improved sleep quality, weight changes of 8-15 lbs in 12 weeks, reduced brain fog, and better mood stability. We track objective biomarkers so you can see measurable progress.', 'Health_Questions', true),
('How long does it take to see results?', 'Most clients notice subjective improvements (energy, sleep, mood) within 2-3 weeks. Measurable biomarker changes typically show up on labs at 6-8 weeks. Full protocol results are assessed at 12 weeks. We set realistic expectations upfront and track progress at every step.', 'Health_Questions', true),
('Do you have client success stories?', 'Absolutely. We have dozens of documented case studies and testimonials on our website. Highlights include a 45-year-old executive who reversed pre-diabetes in 10 weeks, a working mom who eliminated chronic fatigue and lost 22 lbs, and a corporate team that reduced sick days by 34% through our group program.', 'Health_Questions', true),
('What if the program does not work for me?', 'We stand behind our work. If you complete your full program protocol and do not see measurable improvement in your labs and symptoms, we will extend your program at no additional cost until we find what works. We have never had a compliant client not see results.', 'Health_Questions', true),
('How much do your programs cost?', 'Our programs range from $1,500 to $4,500 depending on the program and format:\n\nDiscovery Call — Free\nGroup Programs — Starting at $1,500 (8-12 weeks)\n1-on-1 Programs — Starting at $2,500 (8-12 weeks)\nExecutive Wellness — $4,500/year (quarterly labs + ongoing coaching)\n\nAll programs include lab work, supplements protocol, and coaching. Payment plans are available.', 'Billing_Insurance', true),
('Do you accept insurance?', 'We are an out-of-network provider. We provide superbills that you can submit to your insurance for potential reimbursement — many PPO plans reimburse 50-80% of our fees. We also accept HSA/FSA cards for all services. Our team can help you verify your out-of-network benefits before you start.', 'Billing_Insurance', true),
('Do you offer payment plans?', 'Yes! We offer 3-month and 6-month payment plans with no interest for all programs over $2,000. We also accept HSA/FSA cards, which can make our programs effectively tax-free. Contact us for details on financing options.', 'Billing_Insurance', true),
('What is included in the program fee?', 'Everything you need is included: comprehensive lab panels (typically $800-1,200 value), all 1-on-1 coaching sessions, your personalized protocol, supplement recommendations with discount access, progress tracking, secure messaging with your practitioner between sessions, and access to our client resource library.', 'Billing_Insurance', true),
('Where are you located?', 'Our office is located in downtown Austin, TX. We also serve clients nationwide through our virtual programs. Approximately 60% of our clients work with us entirely remotely with the same great results.', 'General_Info', true),
('What are your office hours?', 'Monday through Friday, 8 AM to 6 PM CT. Saturday appointments available by request. Our team responds to emails and portal messages within one business day. For urgent matters, same-day callbacks are available for active clients.', 'General_Info', true),
('How do I get started?', 'The easiest way to get started is booking a free 15-minute discovery call at fitlogic.com/book. On the call, we will discuss your goals, answer questions, and recommend the best program for you. No pressure, no commitment — just a conversation about what is possible.', 'General_Info', true),
('Can I refer a friend?', 'Yes! We love referrals. When you refer a friend who enrolls in any program, you both receive a $250 credit toward services. There is no limit on referrals. Ask about our Ambassador Program for even more benefits.', 'General_Info', true);